import React from 'react'

const Features = () => {
  return (
   
    <div  className='w-full py-10 text-white'>

<div className='max-w-[1240px] mx-auto'>

    <h1 className='md-text-6xl sm:text-5xl text-3xl font-bold'>What I Do</h1>

    <div className='max-w-[1240px] max-h-[1240px] mx-auto grid md:grid-cols-3 gap-x-8'>
 
    <div className='bg-gray-900 w-full shadow-xl flex flex-col p-5 my-8 rounded-lg hover:scale-105 duration-300'>
               
               
               <h1 className='font-bold md-text-xl sm: 2xl text-xl text-2xl  py-1 border-b mx-8 shadow-xl shadow-cyan-500/50'>Front End Development</h1><br/>
               <p className='text-gray-200'>I learning in creating responsive and user-friendly web applications using HTML, CSS, and React with tailwind css.
                I excel at bringing to life beautiful and functional interfaces that meet the needs of end-users.I tried to do my best to give hardworking and passionate responsive websites.</p>
                
               
            </div>
            <div className='bg-gray-900 w-full shadow-xl flex flex-col p-5 my-8 rounded-lg hover:scale-105 duration-300'>
               
               
               <h1 className='font-bold md-text-xl sm: 2xl text-xl text-2xl  py-1 border-b mx-8 shadow-xl shadow-cyan-500/50'>Back End Development</h1><br/>
               <p className='text-gray-200'>I have experience building scalable and 
               reliable server-side applications   using modern technologies and frameworks like Angular,node ,Mongo DB ,sql and try to learn java and python.
             </p>
                
               
            </div>
              
         

            <div className='bg-gray-900 w-full shadow-xl flex flex-col p-5 my-8 rounded-lg hover:scale-105 duration-300'>
               
               
               <h1 className='font-bold md-text-xl sm: 2xl text-xl text-2xl py-1 border-b mx-8 shadow-xl shadow-cyan-500/50 '>Quality Assuarance</h1><br/>
               <p className='text-gray-200'>I have experience building scalable and 
               The QA team is involved in all stages of a product's development: production, testing, packaging, and delivery. In contrast, quality control (QC) is a narrower process. QC focuses on detecting mistakes, errors, or missed requirements in a product.
             </p>
                
               
            </div>
          
            <div className='bg-gray-900 w-full shadow-xl flex flex-col p-5 my-8 rounded-lg hover:scale-105 duration-300'>
               
               
               <h1 className='font-bold md-text-xl sm: 2xl text-xl text-2xl  py-1 border-b mx-8 shadow-xl shadow-cyan-500/50'>Critical Thinking</h1><br/>
               <p className='text-gray-200'>I have experience building scalable and 
               Critical thinking is the intellectually disciplined process of actively and skillfully conceptualizing, applying, analyzing, synthesizing, and/or evaluating information gathered from, or generated by, observation, experience, reflection, reasoning, or communication, as a guide to belief and action.
             </p>
                
               
            </div>
</div>
    </div>
    </div>
  )
}

export default Features